// <auto-generated />
using System;
using Intranet.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intranet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805130534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Intranet.Models.AiVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiscrepancyDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsLegit")
                        .HasColumnType("bit");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__AiVerifi__3214EC072767F918");

                    b.HasIndex("RequestId");

                    b.ToTable("AiVerifications", "Proc");
                });

            modelBuilder.Entity("Intranet.Models.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DecisionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Approval__3214EC0786C3BDE8");

                    b.HasIndex("ApproverId");

                    b.HasIndex("RequestId");

                    b.ToTable("Approvals", "Proc");
                });

            modelBuilder.Entity("Intranet.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActionBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__AuditLog__3214EC07B30AE5F2");

                    b.ToTable("AuditLogs", "Core");
                });

            modelBuilder.Entity("Intranet.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Departme__3214EC0771E95E4A");

                    b.ToTable("Departments", "Core");
                });

            modelBuilder.Entity("Intranet.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Document__3214EC07D3B174C0");

                    b.HasIndex("RequestId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Documents", "Proc");
                });

            modelBuilder.Entity("Intranet.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC07463E2436");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", "Core");
                });

            modelBuilder.Entity("Intranet.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("PaidById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PopBlobUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Completed");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC072EE57FA6");

                    b.HasIndex("PaidById");

                    b.HasIndex("RequestId");

                    b.ToTable("Payments", "Proc");
                });

            modelBuilder.Entity("Intranet.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiAnalysisNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AiConfidenceScore")
                        .HasColumnType("float");

                    b.Property<string>("AiExtractedVat")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Quotes__3214EC075406B476");

                    b.HasIndex("RequestId");

                    b.ToTable("Quotes", "Proc");
                });

            modelBuilder.Entity("Intranet.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FutureDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPoRequired")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentTiming")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Present");

                    b.Property<string>("QuoteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Requests__3214EC0716E20DA5");

                    b.HasIndex("RequesterId");

                    b.ToTable("Requests", "Proc");
                });

            modelBuilder.Entity("Intranet.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC070DBD3F54");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160E74F2CAD")
                        .IsUnique();

                    b.ToTable("Roles", "Core");
                });

            modelBuilder.Entity("Intranet.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC078173C20E");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534E2A9FE87")
                        .IsUnique();

                    b.ToTable("Users", "Core");
                });

            modelBuilder.Entity("Intranet.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK__UserRole__AF2760AD2302413A");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Core");
                });

            modelBuilder.Entity("Intranet.Models.AiVerification", b =>
                {
                    b.HasOne("Intranet.Models.Request", "Request")
                        .WithMany("AiVerifications")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK__AiVerific__Reque__160F4887");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Intranet.Models.Approval", b =>
                {
                    b.HasOne("Intranet.Models.User", "Approver")
                        .WithMany("Approvals")
                        .HasForeignKey("ApproverId")
                        .IsRequired()
                        .HasConstraintName("FK__Approvals__Appro__778AC167");

                    b.HasOne("Intranet.Models.Request", "Request")
                        .WithMany("Approvals")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK__Approvals__Reque__76969D2E");

                    b.Navigation("Approver");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Intranet.Models.Document", b =>
                {
                    b.HasOne("Intranet.Models.Request", "Request")
                        .WithMany("Documents")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Documents__Reque__7B5B524B");

                    b.HasOne("Intranet.Models.User", "UploadedBy")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedById")
                        .IsRequired()
                        .HasConstraintName("FK__Documents__Uploa__7C4F7684");

                    b.Navigation("Request");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Intranet.Models.Notification", b =>
                {
                    b.HasOne("Intranet.Models.Request", "Request")
                        .WithMany("Notifications")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK__Notificat__Reque__03F0984C");

                    b.HasOne("Intranet.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__02FC7413");

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Intranet.Models.Payment", b =>
                {
                    b.HasOne("Intranet.Models.User", "PaidBy")
                        .WithMany("Payments")
                        .HasForeignKey("PaidById")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__PaidBy__2A164134");

                    b.HasOne("Intranet.Models.Request", "Request")
                        .WithMany("Payments")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__Reques__29221CFB");

                    b.Navigation("PaidBy");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Intranet.Models.Quote", b =>
                {
                    b.HasOne("Intranet.Models.Request", "Request")
                        .WithMany("Quotes")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK__Quotes__RequestI__72C60C4A");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Intranet.Models.Request", b =>
                {
                    b.HasOne("Intranet.Models.User", "Requester")
                        .WithMany("Requests")
                        .HasForeignKey("RequesterId")
                        .IsRequired()
                        .HasConstraintName("FK__Requests__Reques__6C190EBB");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Intranet.Models.User", b =>
                {
                    b.HasOne("Intranet.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__Departmen__60A75C0F");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Intranet.Models.UserRole", b =>
                {
                    b.HasOne("Intranet.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__RoleI__693CA210");

                    b.HasOne("Intranet.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__UserI__68487DD7");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Intranet.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Intranet.Models.Request", b =>
                {
                    b.Navigation("AiVerifications");

                    b.Navigation("Approvals");

                    b.Navigation("Documents");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("Intranet.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Intranet.Models.User", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Documents");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Requests");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
